<a href="https://colab.research.google.com/github/maker-arch/D2LExercises/blob/main/DataManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [17]:
# 1维tensor，指定float
# x = torch.tensor([3,2,3,4], dtype=torch.float32)
x = torch.arange(12, dtype=torch.float32)
x
# inspect the total number of elements
x.numel()
# tensor shape just attr
x.shape
# reshape
X = x.reshape(3,4)
X
# 元素全初始化为0的tensor 也可以torch.zeros((2,3,4))
torch.zeros(2,3,4)
# 元素全初始化为1的tensor
torch.ones((2,3,4))
# creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.
torch.randn(2,3,4)
# create a tensor with Python list

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [27]:
# index -1 start:end
X[-1],X[1:3]
# write elements of a matrix by specifying indices
X[1,2] = 7
X
# 多个elements复制
X[1:2] = 12
X

tensor([[ 0.,  1.,  2.,  3.],
        [12., 12., 12., 12.],
        [ 8.,  9.,  7., 11.]])

In [43]:
# operation
# exp
torch.exp(x)
# + - * / **
x = torch.tensor([1.0, 2,4,8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x ** y
# concatenate on axis0 or axis1
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2,0,1,3.0],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y), axis=0),torch.cat((X,Y),axis=1)
# 逻辑
X == Y,X < Y,X > Y
# sum
# X,X.sum(),X.sum(axis=0),X.sum(axis=1)

(tensor([[False, False, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False,  True,  True, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [45]:
# broadcasting
# x = torch.arange(3).reshape(3,1)
# y = torch.arange(2).reshape(1,2)


x = torch.arange(12).reshape(3,4,1)
y = torch.arange(8).reshape(1,4,2)

x,y,x + y

(tensor([[[ 0],
          [ 1],
          [ 2],
          [ 3]],
 
         [[ 4],
          [ 5],
          [ 6],
          [ 7]],
 
         [[ 8],
          [ 9],
          [10],
          [11]]]),
 tensor([[[0, 1],
          [2, 3],
          [4, 5],
          [6, 7]]]),
 tensor([[[ 0,  1],
          [ 3,  4],
          [ 6,  7],
          [ 9, 10]],
 
         [[ 4,  5],
          [ 7,  8],
          [10, 11],
          [13, 14]],
 
         [[ 8,  9],
          [11, 12],
          [14, 15],
          [17, 18]]]))

In [47]:
# saving memory, edit in place
before = id(Y)
Y = Y + X
id(Y) == before

Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = Y + X
print('id(Z):', id(Z))

before = id(X)
X += Y
id(X) == before

id(Z): 139741165464512
id(Z): 139741165464512


True

In [52]:
# Conversion to Other Python Objects
# to numpy
A = X.numpy()
B = torch.from_numpy(A)
B
# to python scalar
#
x = torch.tensor([4.0])
x, x.item(), float(x), int(x)

(tensor([4.]), 4.0, 4.0, 4)

Run the code in this section. Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.

Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?