<a href="https://colab.research.google.com/github/maker-arch/D2LExercises/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Scalars
x = torch.tensor(3.0)
# x.shape # torch.Size([])标量
y = torch.tensor(2.0)

x + y, x - y, x * y, x / y, x ** y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

In [ ]:
# vectors
x = torch.arange(3)
x, x[2],x[-1],len(x),x.shape

(tensor([0, 1, 2]), tensor(2), tensor(2), 3, torch.Size([3]))

In [ ]:
# matrix
X = torch.arange(12).reshape(4,3)
X

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
X.T # transpose

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [ ]:
# symmetric matrix
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(3,2)
B = A.clone()
A, A + B

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.]]),
 tensor([[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.]]))

In [ ]:
A * B

tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.]])

In [ ]:
# add scalars
a = 2
A = torch.arange(6, dtype=torch.float32).reshape(3,2)
a + A, (a * A).shape

(tensor([[2., 3.],
         [4., 5.],
         [6., 7.]]),
 torch.Size([3, 2]))

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(3,2)
A.sum(), A.shape, A.sum(axis=0), A.sum(axis=1).shape

(tensor(15.), torch.Size([3, 2]), tensor([6., 9.]), torch.Size([3]))

In [ ]:
A.sum(axis=[0,1]) == A.sum()

tensor(True)

In [ ]:
A.mean(), A.sum()/A.numel()

(tensor(2.5000), tensor(2.5000))

In [ ]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([2., 3.]), tensor([2., 3.]))

In [ ]:
sum_A = A.sum(axis=0, keepdim=True)
sum_A, sum_A.shape

torch.Size([1, 2])

In [ ]:
# broadcasting
A/sum_A, A

(tensor([[0.0000, 0.1111],
         [0.3333, 0.3333],
         [0.6667, 0.5556]]),
 tensor([[0., 1.],
         [2., 3.],
         [4., 5.]]))

In [ ]:
A.cumsum(axis=0)

tensor([[0., 1.],
        [2., 4.],
        [6., 9.]])

In [ ]:
x = torch.arange(2, dtype=torch.float32)
y = torch.ones(2, dtype=torch.float32)
x, y, torch.dot(x,y)

(tensor([0., 1.]), tensor([1., 1.]), tensor(1.))

In [ ]:
torch.sum(x * y)

tensor(3.)

In [ ]:
A.shape, x.shape, torch.mv(A,x), A@x # A(3,2) x(3)

RuntimeError: size mismatch, got input (3), mat (3x2), vec (3)

In [ ]:
A.shape, x.shape, torch.mv(A,x), A@x

(torch.Size([3, 2]),
 torch.Size([2]),
 tensor([1., 3., 5.]),
 tensor([1., 3., 5.]))

In [ ]:
B = torch.ones(2,4)
torch.mm(A,B), A @ B

(tensor([[1., 1., 1., 1.],
         [5., 5., 5., 5.],
         [9., 9., 9., 9.]]),
 tensor([[1., 1., 1., 1.],
         [5., 5., 5., 5.],
         [9., 9., 9., 9.]]))

In [ ]:
u = torch.tensor([3.0, 4.0])
torch.norm(u)

tensor(5.)

In [ ]:
torch.abs(u).sum()

tensor(7.)

In [ ]:
torch.norm(torch.ones((4,9)))

tensor(6.)

In [9]:
import torch

# We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)? Write your answer without implementing any code, then check your answer using code.
X = torch.arange(24, dtype=torch.float32).reshape(2,3,4)
len(X),X.size()

# X/X.sum(axis=1) # error cause sum operator doesn't keep the origin dim

X.sum(axis=0).shape,X.sum(axis=1).shape,X.sum(axis=2).shape,X

(torch.Size([3, 4]),
 torch.Size([2, 4]),
 torch.Size([2, 3]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]))

In [10]:
torch.linalg.norm(X) # flat then norm


def l2_norm(X):
  return torch.sqrt(torch.sum(X ** 2))

l2_norm(X),torch.linalg.norm(X)

(tensor(65.7571), tensor(65.7571))

In [23]:
A = torch.ones([2,4])
B = torch.zeros([2,4])
C = torch.ones([2,4])
A,B,C,torch.stack([A,B,C], dim=1),torch.stack([A,B,C], dim=2),torch.stack([A,B,C], dim=0) #stack expects each tensor to be equal size

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[[1., 1., 1., 1.],
          [0., 0., 0., 0.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [0., 0., 0., 0.],
          [1., 1., 1., 1.]]]),
 tensor([[[1., 0., 1.],
          [1., 0., 1.],
          [1., 0., 1.],
          [1., 0., 1.]],
 
         [[1., 0., 1.],
          [1., 0., 1.],
          [1., 0., 1.],
          [1., 0., 1.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [22]:
(torch.stack([A,B,C], dim=2)[:, :, 1] == B).all()

tensor(True)